networks:
  dev_network:
    driver: bridge

services:

  postgres-db:
    container_name: postgres-db
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME} || exit 1"]
      interval: 10s
      retries: 10
      start_period: 60s
      timeout: 10s
    networks:
      - dev_network

